{% set name = "saturn-client" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256:

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - requests
  run:
    - python
    - requests

about:
  home: "https://saturncloud.io/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python library for interacting with Saturn"
  doc_url: https://www.saturncloud.io/docs/
  dev_url: https://github.com/saturncloud/saturn-client

extra:
  recipe-maintainers:
    - jsignell
    - forana
    - hhuuggoo
